### PR TITLE
Delete Detail redirects to Index

### PR DESCRIPTION
**Pull request by taroken6**
- Fixed issue where deleting from Detail would not redirect the user and remain on Detail page with null values.
- Likely an update caused this issue

### CODE REVIEW

**Comment by davidism** [comment]
Seems like `node` should be `null` in this case, not `node.result`. Maybe this code should stay the same and something else should be changed?

**Comment by taroken6** [comment]
Jeff and I were guessing some change caused that previous check to not work anymore. It seems we can change the code somewhere in conveyor-redux, but I'm wondering if there's a reason someone made `node` add a `result` instead of just setting `node` to null.

**Comment by itechify** [comment]
Looks like it can be addressed in conveyor-redux model.ts REMOVE_INSTANCE:
https://github.com/autoinvent/conveyor-redux/blob/33da5d5a1bd1e527d228e33196e1f2517eb0a49f/src/reducers/model.ts#L100

I'm not sure if this will have any side effects though...Doesn't look like it would have side effects in conveyor at least since result is never mentioned in Detail.

**Comment by taroken6** [comment]
Setting `node` to null causes the error `node is undefined` in `TRList` Component.
Would need to make changes to both in Conveyor and Conveyor-Redux if we want to change `node` to null instead of adding a null `result`

**Comment by itechify** [comment]
Ok let's just go with this change for now and make an issue to investigate it in the future. It must have been done for a reason.

Resolve the conflicts (pull and add the change to the new .tsx file for Detail instead of js) and should be good.

**Comment by taroken6** [comment]
Woops, I forgot about those other two commits. Didn't realize we converted Detail to typescript until a couple hours ago

**Pull request merged**
