### PR TITLE
Format search page filters to not wrap on resize

### PR DESCRIPTION
**Pull request by DanielHall977**
Handles comment in issue #152 
If the window is minimized, counts and checkboxes should stay on the same line.
Screenshot from 2021-07-14 10-08-53

### CODE REVIEW

**Comment by davidism** [comment]
This seems like the wrong approach. You should almost never be setting pixel values in CSS. Instead, there are probably relevant boostrap utilities for controlling layout and flow.

**Comment by apastel** [comment]
I would have to agree with David, I think that looking at controlling the breakpoints would be a better method. However CSS is my weak point so I appreciate you attempting to tackle this. I'm happy to tackle it some time later though if it becomes a pain.

**Comment by DanielHall977** [comment]
I've been trying to solve with bootstrap flex class (recommended solution) but I've run into a new problem.
Screenshot from 2021-07-14 13-34-04

**Comment by DanielHall977** [comment]
Got It!
Screenshot from 2021-07-14 14-43-49

**Pull request merged**
