### PR TITLE
Quicksearch initial functionality

### PR DESCRIPTION
**Pull request by aglenister1205**
using this dropdown, user input can be search via the search button or by pressing enter, and it will show all objects with a similar/matching descriptor. These objects can then be selected and if selected the user will be brought to the detail page of that object. 

Note: The separate search page is not up and running yet, this is just the quicksearch on the navbar

### CODE REVIEW

**Comment by robxbob** [comment]
Ideally the search would update upon text change, but It's fine to merge as in for now. Make it on the left side of the models dropdown and include the input field in the navbar. This requires less clicks to "quick search".

**Comment by aglenister1205** [comment]
the search bar updates upon text change, populating the drop down with the results of the search. There currently is no search button, but when the button is created it will bring the user to the search page as opposed to using the navbar's search feature.

**Review by robxbob — COMMENTED** [review]
checked

**Comment by robxbob** [comment]
Make it so that white character is accepted so that I can type words to match a message from Task

**Comment by aglenister1205** [comment]
the above commit should resolve the whitespace issue

**Review by robxbob — COMMENTED** [review]
checked

**Comment by robxbob** [comment]
Issues:
- The search bar in the navbar shows an `x` icon that doesnt do anything .
- After typing a query in the search bar, the user should be able to hit the enter key to be sent to the quick search page. In the quick search page, the input field should already be populated, along with the results. 
- Increase the number of elements that would appear to be 20. It was supposed to be 20 originally for the table content as well, but forgot to change it.

**Comment by aglenister1205** [comment]
this commit should fix those issues, as of right now once navigated to the search page, anything input into the navbar search will no longer populate in the search page search bar, but will still function as a dropdown. Once the search page is left, the navbar search functions as intended, bringing the user to the search page upon enter or use of the search button.

**Comment by robxbob** [comment]
Different Search used in newer release of Conveyor

**Pull request closed without merging**
